version: '3.2'
services:
  sonarqube:
    image: sonarqube:lts-alpine
    ports:
      - 9000:9000
      - 9092:9092
    container_name: sonarqube
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8085:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - /volume1/docker/jenkins/jenkins_home:/var/jenkins_home #Remember that, the tmp directory is designed to be wiped on system reboot.
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - sonarqube